-- Create wastage table
CREATE TABLE IF NOT EXISTS wastage (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    item_name TEXT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    cost_per_unit DECIMAL(10,2) NOT NULL DEFAULT 0,
    reason TEXT
);

-- Enable RLS
ALTER TABLE wastage ENABLE ROW LEVEL SECURITY;

-- Policy for authenticated users (read/write)
CREATE POLICY "Allow authenticated users to manage wastage"
ON wastage
FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Policy for anon (read only if needed, or none)
CREATE POLICY "Allow public read wastage"
ON wastage FOR SELECT
TO anon
USING (true);

CREATE POLICY "Allow public insert wastage"
ON wastage FOR INSERT
TO anon
WITH CHECK (true);
